---
- hosts: all
  become: yes
  tasks:
  - name: i want to installed tree,wget,apche2
    apt:
      name: "{{item}}"
      state: absent
    loop:
       - "{{var1}}"
       - "{{var2}}"
       - "{{var3}}"
       - "{{var4}}"
    ignore_errors: yes
    when: ansible_os_family == "Debian"

  - name: i want to installed tree,wget,apche2
    yum:
      name: "{{item}}"
      state: absent
    loop:
       - "{{var1}}"
       - "{{var2}}"
       - "{{var3}}"
       - "{{var4}}"
    ignore_errors: yes
    register: myresult
    when: ansible_os_family == "RedHat"

  - name: restart htttpd
    service:
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"
          myresult.stderr == ""