---
- hosts: firstnode
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install websever
    apt:
      name: apache2
      state: present

  - name: i want to copy file on server
    template:
       src: index.j2
       dest: /var/www/html/index.html