---
- hosts: all
  become: yes
  tasks:
  - name: I want to install tree
    apt:
     name: tree
     state: present

  - name: I want to install wget
    apt:
     name: wget
     state: present
    when: ansible_os_family == "RedHat"  

  - name: I want to install apache2
    apt:
     name: apache2
     state: absent
    when: ansible_os_family == "RedHat"