---
- hosts: all
  become: yes
  tasks:
  - name: I want to install tree
    apt:
     name: tree
     state: present
    when: ansible_os_family =="Debian"

  - name: I want to install webserber on ubuntu server
    apt:
     name: "{{ubn}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: I want to install wget
    yum:
     name: wget
     state: present
    when: ansible_os_family =="RedHat"
    
  - name: I want to install webserber
    yum:
     name: "{{red{}"
     state: present
    when: ansible_os_family =="RedHat"

  - name: I want to start httpd server
    service:
      name: "{{red}}"
      state: started
    when: ansible_os_family =="RedHat"