---
- hosts: all
  become: yes
  tasks:
  - name: I want to install tree
    apt:
     name: tree
     state: present

  - name: I want to install wget
    apt:
     name: wget
     state: absent
    
  - name: I want to install webserber
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"