---
- hosts: mywebserver
  become: yes
  tasks:
  - name: I want to install java on redhat server
    yum:
      name: "{{javaredhat}}"
      state: present    
    when: ansible_os_family =="RedHat"

  - name: I want to install java on ubuntu server node
    apt:
       name: "{{java_ubuntu}}"
       state: present
    when: ansible_os_family =="Debian"

  - name: Install the 'Gnome desktop' environment group
    yum:
      name: "@^gnome-desktop-environment"
      state: present
    when: ansible_os_family =="RedHat"