---
# tasks file for pproject

- name: i want to install webserver
  apt:
      name: apache2
      state: present
  notify: restartwebserver

- name: i want to create jinja file
  template:
       src: template/web.j2
       dest: /var/www/html/index.html
  notify: restartwebserver