---
# tasks file for mytomcat001

- include_tasks: installjava.yml
- include_tasks: CreateTomcatUser.yml
- include_tasks: InstallTomcat.yml
- include_tasks: UpdatePermissions.yml
- include_tasks: systemdServiceFile.yml
- include_tasks: TomcatWebManagement.yml