---
- name: make the tomcat group to owner of the installation directory
  file:
    path: /opt/tomcat
    group: tomcat
    recurse: yes
    state: directory
    
- name: give the tomcat group read access to the conf directory
  file:
    path: /opt/tomcat/conf
    recurse: yes
    state: directory
    mode: g+r

- name: give the tomcat group execute access to the directory itself
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x

- name: Make the tomcat to owner of the webapps/work/temp/logs dir
  file:
    path: "{{item}}"
    recurse: yes
    owner: tomcat
    state: directory
  loop:
    - /opt/tomcat/webapps/
    - /opt/tomcat/work/
    - /opt/tomcat/temp/
    - /opt/tomcat/logs/
    