---
- name: i want to create a tomcat group
  group:
    name: tomcat
    state: present

- name: i want to create tomcad user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    home: /opt/tomcat
    state: present