---
- name: create the systemd service file
  template:
      src: template/service.j2
      dest: /etc/systemd/system/tomcat.service

- name: enable and reload the systemd
  systemd:
    name: tomcat
    daemon_reload: yes
    state: started
    enabled: True